name: Block Merge Based on Time
 
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  schedule:
    - cron: "*/45 6 * * *"  #  Runs daily at 06:45 AM UTC (12:15 PM IST)
 
jobs:
  block:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      statuses: write
    steps:
      - uses: yykamei/block-merge-based-on-time@main
        id: block
        with:
          timezone: Asia/Kolkata
          after: "12:15"
          before: "12:30"
          base-branches: "main"
          prohibited-days-dates: ""  # No specific days blocked, applies every day
      - run: |
          echo "PR Blocked: ${{ steps.block.outputs.pr-blocked }}"
      - run: |
          echo "Current Time: $(date)"
        if: github.event_name == 'pull_request'
